import { z } from 'zod';

export const allowedEventNames = [
  'tool_viewed',
  'tool_started',
  'tool_completed',
  'tool_validation_failed',
  'result_generated',
  'result_printed',
  'result_downloaded',
  'result_copied',
  'result_shared',
  'related_tool_opened',
  'search_performed',
  'search_zero_results',
  'category_viewed',
  'featured_tool_opened',
  'report_error_opened',
  'feedback_submitted',
] as const;

export type AnalyticsEventName = (typeof allowedEventNames)[number];
export type SafeAnalyticsProperties = Record<string, string | number | boolean | string[] | undefined>;

/**
 * Analytics is intentionally limited to generic, low-cardinality metadata.
 * Keep this schema independent from the runtime registry so the client bundle
 * cannot pull calculation inputs, policies or React definitions into the
 * analytics boundary.
 */
export const analyticsPayloadSchema = z
  .object({
    toolId: z
      .string()
      .trim()
      .min(1)
      .max(120)
      .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
    category: z
      .string()
      .trim()
      .min(1)
      .max(80)
      .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
    format: z.enum(['pdf', 'png', 'jpeg', 'webp', 'svg', 'csv', 'vcf', 'zip', 'html', 'text']),
    pageSize: z.enum([
      'a4',
      'summary',
      'qr',
      'standee',
      'thermal-58',
      'thermal-80',
      'label-4x6',
      'label-sheet',
    ]),
    errorCodes: z
      .array(
        z
          .string()
          .trim()
          .min(1)
          .max(80)
          .regex(/^[a-z0-9._-]+$/i),
      )
      .max(20),
  })
  .partial()
  .strict();

export type AnalyticsPayload = z.infer<typeof analyticsPayloadSchema>;

const allowedAnalyticsPropertyNames = new Set(['toolId', 'category', 'format', 'pageSize', 'errorCodes']);

const forbiddenPropertyNames = new Set([
  'amount',
  'gstAmount',
  'taxableValue',
  'totalAmount',
  'ratePercent',
  'customRate',
  'ratePresetId',
  'cgstAmount',
  'sgstAmount',
  'sgstOrUtgstAmount',
  'igstAmount',
  'supplyType',
  'calculationMode',
  'mode',
  'policyVersion',
  'beginningValue',
  'endingValue',
  'years',
  'investmentCost',
  'finalValue',
  'profit',
  'percentage',
  'result',
  'rawInput',
  'url',
  'normalizedUrl',
  'payload',
  'name',
  'payeeName',
  'note',
  'address',
  'gstin',
  'upiId',
  'wifiPassword',
  'documentContents',
  'businessName',
  'businessAddress',
  'phone',
  'email',
  'website',
  'tagline',
  'cin',
  'registrationNumber',
  'additionalContact',
  'socialHandle',
  'recipientName',
  'recipientAddress',
  'subject',
  'body',
  'letterDate',
  'signatoryName',
  'signatoryDesignation',
  'invoiceNumber',
  'invoiceDate',
  'dueDate',
  'supplierLegalName',
  'supplierGstin',
  'supplierAddress',
  'supplierPhone',
  'supplierEmail',
  'recipientLegalName',
  'recipientGstin',
  'recipientAddress',
  'recipientPhone',
  'recipientEmail',
  'items',
  'quoteNumber',
  'quoteDate',
  'validUntil',
  'customerName',
  'customerAddress',
  'customerEmail',
  'customerPhone',
  'paymentDetails',
  'notes',
  'terms',
  'itemsJson',
  'personName',
  'designation',
  'cardPhone',
  'cardEmail',
  'cardWebsite',
  'cardAddress',
  'cardTagline',
  'cardNote',
  'prefix',
  'financialYear',
  'nextNumber',
  'padding',
  'receiptNumber',
  'receiptDate',
  'receivedFrom',
  'paymentPurpose',
  'paymentMethod',
  'transactionReference',
  'paymentNote',
  'invoiceReference',
  'customerAddress',
  'footerText',
  'signaturePlaceholder',
  'logo',
  'logoDataUrl',
  'dataUrl',
  'originalName',
  'amountWords',
  'revenue',
  'totalCost',
  'unitCost',
  'sellingPrice',
  'fixedCosts',
  'sellingPricePerUnit',
  'variableCostPerUnit',
  'targetMargin',
  'discountPercent',
  'taxRate',
  'assessmentYear',
  'taxRegime',
  'cityType',
  'basicSalary',
  'dearnessAllowance',
  'hraReceived',
  'rentPaid',
  'accommodationStatus',
  'periodPattern',
  'turnoverBasedCommission',
  'taxPeriod',
  'residentialStatus',
  'ageCategory',
  'salaryIncome',
  'housePropertyIncome',
  'otherIncome',
  'deductions',
  'taxAlreadyPaid',
  'paymentDate',
  'creditDate',
  'paymentType',
  'payeeType',
  'payeeResidency',
  'panStatus',
  'paymentAmount',
  'cumulativeAmount',
  'regime',
  'taxableIncome',
  'bookProfit',
  'scheme',
  'entityType',
  'activity',
  'resident',
  'turnover',
  'cashReceiptPercent',
  'vehicleCount',
  'vehicleMonths',
  'vehicleType',
  'policyDate',
  'basicAnnual',
  'dearnessAllowanceAnnual',
  'hraAnnual',
  'otherAllowancesAnnual',
  'bonusAnnual',
  'employerPfAnnual',
  'gratuityProvisionAnnual',
  'insuranceAnnual',
  'otherBenefitsAnnual',
  'state',
  'grossAnnualEarnings',
  'annualExemptions',
  'annualDeductions',
  'employeePfAnnual',
  'professionalTaxAnnual',
  'otherDeductionsAnnual',
  'monthlyBasicDa',
  'wageCeiling',
  'employeeRate',
  'employerRate',
  'epsRate',
  'edliRate',
  'adminCharge',
  'membership',
  'higherWageOption',
  'epsEligible',
  'employmentType',
  'event',
  'completedYears',
  'additionalMonths',
  'lastDrawnWages',
  'gratuityCap',
  'exemption',
  'openingCash',
  'cashInflows',
  'cashOutflows',
  'oneOffOutflows',
  'periodMonths',
  'totalOutflows',
  'totalInflows',
  'currentCash',
  'monthlyOutflows',
  'monthlyInflows',
  'productCost',
  'platformFeePercent',
  'shippingCost',
  'paymentFeePercent',
  'returnCost',
  'taxCost',
  'adSpend',
  'attributedRevenue',
  'otherVariableCosts',
  'orderValue',
  'codFee',
  'forwardShipping',
  'returnShipping',
  'rtoRate',
  'returnLoss',
  'cashCycleCost',
  'loanAmount',
  'annualRatePercent',
  'tenureMonths',
  'processingFee',
  'resetAfterMonths',
  'resetAnnualRatePercent',
  'monthlyContribution',
  'annualExpectedReturnPercent',
  'contributionTiming',
  'principal',
  'compoundingFrequency',
  'cashFlows',
  'guessPercent',
  'amountA',
  'annualRateA',
  'termMonthsA',
  'processingFeeA',
  'prepaymentFeeA',
  'rateTypeA',
  'resetAfterMonthsA',
  'resetAnnualRateA',
  'amountB',
  'annualRateB',
  'termMonthsB',
  'processingFeeB',
  'prepaymentFeeB',
  'rateTypeB',
  'resetAfterMonthsB',
  'resetAnnualRateB',
  'salesMarketingCost',
  'attributionWindowMonths',
  'newCustomers',
  'paidNewCustomers',
  'paidAcquisitionCost',
  'arpuMonthly',
  'grossMarginPercent',
  'monthlyChurnPercent',
  'churnLowPercent',
  'churnHighPercent',
  'churnStability',
  'mrr',
  'priorMrr',
  'newMrr',
  'expansionMrr',
  'contractionMrr',
  'churnedMrr',
  'customers',
  'priorCustomers',
  'churnedCustomers',
  'profitMarginPercent',
  'annualRevenue',
  'revenueMultipleLow',
  'revenueMultipleHigh',
  'preMoneyValuation',
  'investmentAmount',
  'founderOwnershipPercent',
  'existingInvestorOwnershipPercent',
  'otherOwnershipPercent',
  'postMoneyOptionPoolPercent',
  'fullyDilutedSharesBefore',
  'grantShares',
  'vestedPercent',
  'exercisedShares',
  'exerciseDate',
  'exercisePrice',
  'fairMarketValue',
  'salePrice',
  'taxTreatment',
  'illustrativeTaxRatePercent',
  'fulfillment',
  'referralFeePercent',
  'shippingFee',
  'closingFeeOverride',
  'otherFee',
  'feeGstRatePercent',
  'paymentMode',
  'commissionFeePercent',
  'collectionFeePercent',
  'fixedFeeOverride',
  'assistantInput',
  'input',
  'prompt',
  'draft',
  'draftText',
  'suggestions',
  'sections',
  'metrics',
  'redactedFields',
  'transmittedFields',
  'query',
  'kind',
  'returnType',
  'taxpayerType',
  'period',
  'assetCost',
  'residualValue',
  'usefulLifeYears',
  'openingWdv',
  'daysInService',
  'method',
  'salaryAmount',
  'salaryPeriod',
  'salaryDefinition',
  'gender',
  'month',
  'principal',
  'invoiceDate',
  'acceptedDate',
  'agreedPaymentDays',
  'bankRatePercent',
  'bankRateEffectiveOn',
  'enterpriseType',
  'fromCurrency',
  'toCurrency',
  'manualRate',
]);

function sanitizeAnalyticsProperties(properties: SafeAnalyticsProperties): AnalyticsPayload {
  if (!properties || typeof properties !== 'object' || Array.isArray(properties)) return {};

  const candidate = Object.fromEntries(
    Object.entries(properties).filter(
      ([key, value]) =>
        value !== undefined && allowedAnalyticsPropertyNames.has(key) && !forbiddenPropertyNames.has(key),
    ),
  );
  const parsed = analyticsPayloadSchema.safeParse(candidate);
  if (parsed.success) return parsed.data;

  // Keep valid generic metadata when one field is malformed, but never let a
  // rejected value through and never forward unknown keys.
  const validEntries: Array<[string, unknown]> = [];
  for (const key of Object.keys(candidate)) {
    const result = analyticsPayloadSchema.safeParse({ [key]: candidate[key] });
    if (result.success) validEntries.push([key, result.data[key as keyof AnalyticsPayload]]);
  }
  return Object.fromEntries(validEntries) as AnalyticsPayload;
}

export function trackEvent(event: AnalyticsEventName, properties: SafeAnalyticsProperties = {}) {
  if (typeof window === 'undefined' || !allowedEventNames.includes(event)) return;

  const safeProperties = sanitizeAnalyticsProperties(properties);

  // The MVP deliberately has no third-party analytics transport. This allowlist is the seam for one later.
  window.dispatchEvent(
    new CustomEvent('karobarkit:analytics', { detail: { event, properties: safeProperties } }),
  );
}
