import { DOCUMENT_LAST_REVIEWED } from '@/domain/documents/constants';
import type { SourceReference, ToolCapability } from './types';

export const TOOL_LAST_REVIEWED = '2026-08-08';

export function liveLocalMetadata({
  riskTier,
  reviewCadenceDays,
  policyDependencies = [],
  method,
  lastVerified,
  effectiveFrom,
  reviewerRole = 'Product and domain review',
  reviewerStatus = 'not-required',
  lifecycle = 'live',
  featureFlag,
  goldenFixtureIds = [],
  capabilities = [],
  privacyClassification = 'local-only',
  executionMode = privacyClassification,
}: {
  riskTier: 'A' | 'B' | 'C' | 'D';
  reviewCadenceDays: number;
  policyDependencies?: string[];
  method: string;
  lastVerified: string;
  effectiveFrom?: string;
  reviewerRole?: string;
  reviewerStatus?: 'not-required' | 'pending' | 'approved';
  lifecycle?: 'internal' | 'beta' | 'live' | 'stale-disabled' | 'retired';
  featureFlag?: string;
  goldenFixtureIds?: string[];
  capabilities?: readonly ToolCapability[];
  privacyClassification?:
    'local-only' | 'local-with-bundled-data' | 'network-required' | 'optional-cloud-sync';
  executionMode?: 'local-only' | 'local-with-bundled-data' | 'network-required' | 'optional-cloud-sync';
}) {
  return {
    capabilities,
    privacyClassification,
    executionMode,
    lifecycle,
    featureFlag,
    governance: {
      owner: 'KarobarKit product and domain team',
      riskTier,
      reviewCadenceDays,
      policyDependencies,
      goldenFixtureIds,
    },
    trust: {
      method,
      effectiveFrom,
      lastVerified,
      reviewer: {
        status: reviewerStatus,
        role: reviewerRole,
      },
    },
  };
}

export const cagrSource: SourceReference = {
  id: 'cagr-standard-financial-mathematics',
  title: 'Compound annual growth rate formula reference',
  publisher: 'Investopedia',
  url: 'https://www.investopedia.com/terms/c/cagr.asp',
  lastChecked: TOOL_LAST_REVIEWED,
  evidenceLevel: 'editorial',
};

export const roiSource: SourceReference = {
  id: 'roi-standard-financial-ratio',
  title: 'Return on investment definition and formula',
  publisher: 'Investopedia',
  url: 'https://www.investopedia.com/terms/r/returnoninvestment.asp',
  lastChecked: TOOL_LAST_REVIEWED,
  evidenceLevel: 'editorial',
};

export const qrStandardSource: SourceReference = {
  id: 'qr-code-standard-overview',
  title: 'QR Code two-dimensional symbol overview',
  publisher: 'DENSO WAVE',
  url: 'https://www.qrcode.com/en/about/',
  lastChecked: TOOL_LAST_REVIEWED,
  evidenceLevel: 'authoritative',
};

export const urlStandardSource: SourceReference = {
  id: 'whatwg-url-standard',
  title: 'URL Standard',
  publisher: 'WHATWG',
  url: 'https://url.spec.whatwg.org/',
  lastChecked: TOOL_LAST_REVIEWED,
  evidenceLevel: 'authoritative',
};

export const upiSource: SourceReference = {
  id: 'npci-upi-deep-linking-parameters',
  title: 'UPI QR key deep-linking parameters',
  publisher: 'National Payments Corporation of India',
  url: 'https://www.npci.org.in/PDF/npci/upi/circular/2017/Circular18_BankCompliances_to_enbaleUPIMerchantecosystem_0.pdf',
  lastChecked: TOOL_LAST_REVIEWED,
  evidenceLevel: 'official',
};

export const sharedAnalyticsPolicy = {
  allowedEvents: [
    'tool_viewed',
    'tool_started',
    'tool_completed',
    'tool_validation_failed',
    'result_generated',
    'result_printed',
    'result_downloaded',
    'result_copied',
    'result_shared',
    'related_tool_opened',
  ],
  // Runtime analytics validation lives in src/lib/analytics and deliberately
  // does not import the registry. Keep this metadata list synchronized with
  // that small client-side schema for documentation and release validation.
  allowedProperties: ['toolId', 'category', 'format', 'pageSize', 'errorCodes'],
  forbiddenProperties: [
    'beginningValue',
    'endingValue',
    'years',
    'investmentCost',
    'finalValue',
    'profit',
    'percentage',
    'amount',
    'result',
    'rawInput',
    'url',
    'normalizedUrl',
    'payload',
    'upiId',
    'payeeName',
    'note',
    'wifiPassword',
    'ssid',
    'message',
    'fullName',
    'organization',
    'reviewUrl',
    'originalName',
    'fileContents',
    'splitPages',
    'businessName',
    'businessAddress',
    'phone',
    'email',
    'website',
    'tagline',
    'gstin',
    'cin',
    'registrationNumber',
    'additionalContact',
    'socialHandle',
    'recipientName',
    'recipientAddress',
    'body',
    'receiptNumber',
    'receiptDate',
    'receivedFrom',
    'paymentPurpose',
    'paymentMethod',
    'transactionReference',
    'paymentNote',
    'invoiceReference',
    'customerAddress',
    'signatoryName',
    'signatoryDesignation',
    'invoiceNumber',
    'invoiceDate',
    'dueDate',
    'supplierLegalName',
    'supplierGstin',
    'supplierAddress',
    'supplierPhone',
    'supplierEmail',
    'recipientLegalName',
    'recipientGstin',
    'recipientAddress',
    'recipientPhone',
    'recipientEmail',
    'items',
    'quoteNumber',
    'quoteDate',
    'validUntil',
    'customerName',
    'customerAddress',
    'customerEmail',
    'customerPhone',
    'paymentDetails',
    'notes',
    'terms',
    'quotationItems',
    'itemsJson',
    'personName',
    'designation',
    'cardPhone',
    'cardEmail',
    'cardWebsite',
    'cardAddress',
    'cardTagline',
    'cardNote',
    'prefix',
    'financialYear',
    'nextNumber',
    'padding',
    'documentContents',
    'logo',
    'revenue',
    'totalCost',
    'unitCost',
    'sellingPrice',
    'fixedCosts',
    'sellingPricePerUnit',
    'variableCostPerUnit',
    'targetMargin',
    'discountPercent',
    'taxRate',
    'assessmentYear',
    'taxRegime',
    'cityType',
    'basicSalary',
    'dearnessAllowance',
    'hraReceived',
    'rentPaid',
    'accommodationStatus',
    'periodPattern',
    'turnoverBasedCommission',
    'taxPeriod',
    'residentialStatus',
    'ageCategory',
    'salaryIncome',
    'housePropertyIncome',
    'otherIncome',
    'deductions',
    'taxAlreadyPaid',
    'paymentDate',
    'creditDate',
    'paymentType',
    'payeeType',
    'payeeResidency',
    'panStatus',
    'paymentAmount',
    'cumulativeAmount',
    'regime',
    'taxableIncome',
    'bookProfit',
    'scheme',
    'entityType',
    'activity',
    'resident',
    'turnover',
    'cashReceiptPercent',
    'vehicleCount',
    'vehicleMonths',
    'vehicleType',
    'policyDate',
    'basicAnnual',
    'dearnessAllowanceAnnual',
    'hraAnnual',
    'otherAllowancesAnnual',
    'bonusAnnual',
    'employerPfAnnual',
    'gratuityProvisionAnnual',
    'insuranceAnnual',
    'otherBenefitsAnnual',
    'state',
    'grossAnnualEarnings',
    'annualExemptions',
    'annualDeductions',
    'employeePfAnnual',
    'professionalTaxAnnual',
    'otherDeductionsAnnual',
    'monthlyBasicDa',
    'wageCeiling',
    'employeeRate',
    'employerRate',
    'epsRate',
    'edliRate',
    'adminCharge',
    'membership',
    'higherWageOption',
    'epsEligible',
    'employmentType',
    'event',
    'completedYears',
    'additionalMonths',
    'lastDrawnWages',
    'gratuityCap',
    'exemption',
    'openingCash',
    'cashInflows',
    'cashOutflows',
    'oneOffOutflows',
    'periodMonths',
    'totalOutflows',
    'totalInflows',
    'currentCash',
    'monthlyOutflows',
    'monthlyInflows',
    'productCost',
    'platformFeePercent',
    'shippingCost',
    'paymentFeePercent',
    'returnCost',
    'taxCost',
    'adSpend',
    'attributedRevenue',
    'otherVariableCosts',
    'orderValue',
    'codFee',
    'forwardShipping',
    'returnShipping',
    'rtoRate',
    'returnLoss',
    'cashCycleCost',
    'loanAmount',
    'annualRatePercent',
    'tenureMonths',
    'processingFee',
    'resetAfterMonths',
    'resetAnnualRatePercent',
    'monthlyContribution',
    'annualExpectedReturnPercent',
    'contributionTiming',
    'principal',
    'compoundingFrequency',
    'cashFlows',
    'guessPercent',
    'amountA',
    'annualRateA',
    'termMonthsA',
    'processingFeeA',
    'prepaymentFeeA',
    'rateTypeA',
    'resetAfterMonthsA',
    'resetAnnualRateA',
    'amountB',
    'annualRateB',
    'termMonthsB',
    'processingFeeB',
    'prepaymentFeeB',
    'rateTypeB',
    'resetAfterMonthsB',
    'resetAnnualRateB',
    'salesMarketingCost',
    'attributionWindowMonths',
    'newCustomers',
    'paidNewCustomers',
    'paidAcquisitionCost',
    'arpuMonthly',
    'grossMarginPercent',
    'monthlyChurnPercent',
    'churnLowPercent',
    'churnHighPercent',
    'churnStability',
    'mrr',
    'priorMrr',
    'newMrr',
    'expansionMrr',
    'contractionMrr',
    'churnedMrr',
    'customers',
    'priorCustomers',
    'churnedCustomers',
    'profitMarginPercent',
    'annualRevenue',
    'revenueMultipleLow',
    'revenueMultipleHigh',
    'preMoneyValuation',
    'investmentAmount',
    'founderOwnershipPercent',
    'existingInvestorOwnershipPercent',
    'otherOwnershipPercent',
    'postMoneyOptionPoolPercent',
    'fullyDilutedSharesBefore',
    'grantShares',
    'vestedPercent',
    'exercisedShares',
    'exerciseDate',
    'exercisePrice',
    'fairMarketValue',
    'salePrice',
    'taxTreatment',
    'illustrativeTaxRatePercent',
    'fulfillment',
    'referralFeePercent',
    'shippingFee',
    'closingFeeOverride',
    'otherFee',
    'feeGstRatePercent',
    'paymentMode',
    'commissionFeePercent',
    'collectionFeePercent',
    'fixedFeeOverride',
    'assistantInput',
    'input',
    'prompt',
    'draft',
    'draftText',
    'suggestions',
    'sections',
    'metrics',
    'redactedFields',
    'transmittedFields',
    'query',
    'kind',
    'returnType',
    'taxpayerType',
    'period',
    'mode',
    'assetCost',
    'residualValue',
    'usefulLifeYears',
    'openingWdv',
    'ratePercent',
    'daysInService',
    'method',
    'salaryAmount',
    'salaryPeriod',
    'salaryDefinition',
    'gender',
    'month',
    'principal',
    'invoiceDate',
    'acceptedDate',
    'agreedPaymentDays',
    'bankRatePercent',
    'bankRateEffectiveOn',
    'enterpriseType',
    'fromCurrency',
    'toCurrency',
    'manualRate',
  ],
};

export const documentSource: SourceReference = {
  id: 'css-paged-media-a4-printing',
  title: 'CSS Paged Media Module Level 3',
  publisher: 'World Wide Web Consortium',
  url: 'https://www.w3.org/TR/css-page-3/',
  lastChecked: DOCUMENT_LAST_REVIEWED,
  evidenceLevel: 'authoritative',
};

export const documentPrivacyNote =
  'Business details, document text and logos are processed locally in this browser. They are not sent to a server, saved by default or included in analytics.';
